language: python
python:
  - "3.5"


# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments


# Clean and don't fail
install:
  - rm -rf public || exit 0
  - pip install -r requirements.txt

# Build the website
script:
  - cd docs && make html
  - pwd
  - ghp-import -n -m "Publish docs" -b gh-pages _build/html
  - git push -u origin gh-pages

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
